async page => {
 const base=page.url().replace(/\/$/,'');
 let version='v1';
 const file={id:'a',path:'src/calc.js',version:'v1',status:'modified',label:'calc.js',folder:'src',type:'JS',tone:'lime',added:1,removed:1,sourceAvailable:true,lines:[['removed','1','export const double = x => x;'],['added','1','export const double = x => x * 2;']]};
 const second={...file,id:'b',path:'src/calc.test.js',label:'calc.test.js',version:'t1'};
 const snapshot=()=>({repoId:'ui-test',base:'head-a',head:'head-a',branch:'main',snapshotId:'snapshot-'+version,generatedAt:new Date().toISOString(),workspaceName:'Mobile fixture',files:[{...file,version},second]});
 const guide={title:'Trace the doubling change',summary:'Review the behavior and the boundary.',assumptions:['Only two changed files are included.'],steps:['Intent','Trace','Verify'].map((title)=>({title,explanation:'The function returns its input multiplied by two.',reviewPointers:[{text:'Check the zero input edge case.',citation:{fileId:'a',side:'new',startLine:1,endLine:1}}],citations:[{fileId:'a',side:'new',startLine:1,endLine:1}]}))};
 const scope={includedPaths:['src/calc.js','src/calc.test.js'],excludedCount:0};
 await page.route('**/api/**',async route=>{
  const raw=route.request().url(),path='/api/'+raw.split('/api/')[1].split('?')[0]; const param=(name)=>decodeURIComponent((raw.match(new RegExp('[?&]'+name+'=([^&]+)'))||[])[1]||'');
  let body;
  if(path==='/api/snapshot')body=snapshot();
  else if(path==='/api/config')body={aiEnabled:true,provider:'codex',message:'Codex · existing ChatGPT plan'};
  else if(path==='/api/file')body={snapshotId:param('snapshotId'),path:param('path'),id:'a',version,source:'export const double = x => x * 2;\n',sourceAvailable:true};
  else if(path==='/api/walkthrough')body={guide,scope,snapshotId:'snapshot-'+version,selectedId:'a'};
  else if(path.endsWith('/stream')) {await route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'delta',text:'For zero, '})+'\n'+JSON.stringify({type:'done',text:'For zero, the result is zero.'})+'\n'});return;}
  else body={error:'Unexpected route'};
  await route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.setViewportSize({width:390,height:844});
 await page.goto(base);await page.getByRole('heading',{name:'calc.js',exact:true}).waitFor();
 await page.getByRole('button',{name:'Open files',exact:true}).click();
 await page.goBack();
 if(await page.locator('#file-panel').getAttribute('aria-hidden')!=='true')throw Error('Back did not close file drawer');
 await page.getByRole('button',{name:'Open code guide',exact:true}).click();
 await page.getByRole('button',{name:'Start overview',exact:true}).click();
 await page.getByRole('heading',{name:'Trace the doubling change',exact:true}).waitFor();
 await page.getByRole('button',{name:'Next',exact:true}).click();
 if(!await page.getByRole('heading',{name:'Trace',exact:true}).isVisible())throw Error('Step did not advance');
 if(await page.getByText('Reviewed',{exact:true}).count())throw Error('Understanding auto-reviewed a file');
 await page.locator('#walk-draft').fill('Give an example');
 await page.getByRole('button',{name:'Ask guide',exact:true}).click();
 await page.getByText('For zero, the result is zero.',{exact:true}).waitFor();
 await page.screenshot({path:'/tmp/patchwork-walkthrough-phone.png'});
 await page.getByRole('button',{name:'src/calc.js · new 1–1',exact:true}).click();
 await page.locator('.citation-highlight').first().waitFor();
 if(!await page.getByRole('tab',{name:'Source',exact:true}).getAttribute('aria-selected').then(v=>v==='true'))throw Error('Citation did not show source');
 await page.getByRole('button',{name:'Open code guide',exact:true}).click();
 await page.getByRole('tab',{name:'Conversation',exact:true}).click();
 await page.locator('#chat-draft').fill('Keep my draft');
 await page.getByRole('button',{name:'Close code guide',exact:true}).click();
 await page.getByRole('tab',{name:'Notes (0)',exact:true}).click();
 await page.locator('#note-text').fill('Private question');
 await page.getByRole('button',{name:'Save question',exact:true}).click();
 await page.getByText('Question saved privately on this device.',{exact:true}).last().waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Open code guide',exact:true}).click();
 await page.getByRole('heading',{name:'Trace',exact:true}).waitFor();
 if(await page.evaluate(async()=>{const m=await import('/src/main.js');return m.data.notes.length;})!==1)throw Error('Saved note lost on reload');
 await page.getByRole('tab',{name:'Conversation',exact:true}).click();
 if(await page.locator('#chat-draft').inputValue()!=='Keep my draft')throw Error('Chat draft lost on reload');
 await page.getByRole('button',{name:'Send question',exact:true}).click();
 await page.getByText('For zero, the result is zero.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Close code guide',exact:true}).click();
 await page.getByRole('button',{name:'Reviewed & next',exact:false}).click();
 await page.getByRole('heading',{name:'calc.test.js',exact:true}).waitFor();
 version='v2';
 await page.getByRole('button',{name:'Open files',exact:true}).click();
 await page.getByRole('button',{name:'Refresh',exact:false}).click();
 await page.getByRole('button',{name:/calc.js/}).first().click();
 if(await page.locator('.file-row.selected .review-state').getAttribute('aria-label')!=='Needs review')throw Error('Changed file stayed reviewed');
 await page.screenshot({path:'/tmp/patchwork-review-phone.png'});
 await page.setViewportSize({width:900,height:900});
 await page.getByRole('button',{name:'Code guide',exact:true}).click();
 await page.getByRole('tab',{name:'Walkthrough',exact:true}).click();
 await page.getByRole('button',{name:'Start overview',exact:true}).waitFor();
 await page.screenshot({path:'/tmp/patchwork-review-tablet.png'});
 return ('PASS phone walkthrough/citation/followup; understood != reviewed; reload progress/draft; changed revision reset; tablet guide.');
}
