import assert from 'node:assert/strict';
import { buildDeepManifest, validateDeepSection, deepSpeechChunks } from '../deep-review.mjs';
import { createAgentGuideService } from '../agent-guide-service.mjs';
import { sanitizeDeepWorkspace, createDeepReviewUI } from '../src/deep-review.js';

const source=Array.from({length:76},(_,i)=>i%29===0?'':`const value${i} = ${i};`).join('\n');
const files=[{path:'src/change.js',id:'code',lines:[['added','1','x']]},{path:'package-lock.json',id:'lock',lines:[]},{path:'image.png',id:'binary',binary:true,sourceReason:'Binary source'}];
const captured=new Map([['src/change.js',source],['package-lock.json','{"lockfileVersion":3}'],['image.png',null]]);
const repository={snapshot:{repoId:'repo',snapshotId:'snapshot-1',files},read(path){return {source:captured.get(path),reason:path==='image.png'?'Binary source':null};}};
const manifest=buildDeepManifest(repository);
const code=manifest.filter(item=>item.kind==='code');
assert.equal(code[0].startLine,1);
assert.equal(code.at(-1).endLine,76);
for(let i=1;i<code.length;i++)assert.equal(code[i].startLine,code[i-1].endLine+1);
assert(code.every(item=>item.endLine-item.startLine+1<=30));
assert.equal(manifest.at(-2).kind,'summary');
assert.match(manifest.at(-2).summary,/Generated or lockfile/);
assert.match(manifest.at(-1).summary,/Binary/);
const response=section=>({explanations:[{startLine:section.startLine,endLine:section.startLine,text:'These lines define the values used by this file.'},{startLine:section.startLine+1,endLine:section.endLine,text:'The remaining lines provide the values.'}],pointers:[{text:'Check how these values are consumed.',citation:{path:'src/change.js',side:'new',startLine:section.startLine,endLine:section.startLine}}]});
assert.equal(validateDeepSection(response(code[0]),repository,code[0]).pointers[0].citation.fileId,'code');
assert.throws(()=>validateDeepSection({...response(code[0]),explanations:[{...response(code[0]).explanations[0],startLine:2}]},repository,code[0]),/without gaps/);
assert.throws(()=>validateDeepSection({...response(code[0]),pointers:[{text:'Bad',citation:{path:'src/change.js',side:'new',startLine:999,endLine:999}}]},repository,code[0]),/must cite/);
const audioParts=deepSpeechChunks('A complete explanation. '.repeat(120));assert(audioParts.length>1);assert(audioParts.every(part=>part.length<=900));
let saved;
const storage={load:()=>saved,save:value=>{saved=structuredClone(value);},saveSnapshot:()=>{},loadSnapshot:()=>null};
const snapshots={getRepository:()=>repository,exportRecord:()=>({snapshot:repository.snapshot})};
for(const provider of ['codex','claude']){
 let calls=0;
 const ai={async generate(prompt,options){calls++;assert.equal(options.repositoryTools,undefined,`${provider} must receive bounded source, not Codex-only tools`);assert.match(prompt,/TARGET:/);const match=/target new lines (\d+)-(\d+)/.exec(prompt);return {status:200,body:{text:JSON.stringify(response({startLine:Number(match[1]),endLine:Number(match[2])}))}};}};
 saved=undefined;
 const service=createAgentGuideService(snapshots,ai,{storage});
 const id=`deep-${provider}-session-001`;
 const started=service.startDeep({requestId:id,snapshotId:'snapshot-1'});
 assert.equal(started.mode,'deep');assert.equal(calls,0,'Opening deep mode must not call a model');
 const first=service.deepSection({requestId:`section-${provider}-request-01`,conversationId:id,index:0});
 assert(first.run);assert.equal((await service.runs.wait(first.run.id)).status,'completed');assert.equal(calls,1);
 assert.equal(Object.keys(service.conversation(id).explanations).length,1,'Later sections must not block the first');
 service.advanceDeep({conversationId:id,position:0,group:1});
 assert.equal(service.conversation(id).group,1,'The exact line group should be saved');
 assert.throws(()=>service.advanceDeep({conversationId:id,position:0,group:2}),/line group/);
 const restoredGroup=sanitizeDeepWorkspace({activeId:id,records:{[id]:service.conversation(id)}});
 assert.equal(restoredGroup.records[id].group,1);
 assert.equal(sanitizeDeepWorkspace({activeId:id,records:{[id]:{...service.conversation(id),group:99}}}).records[id].group,1,'Invalid saved positions are clamped');
 service.advanceDeep({conversationId:id,position:1});
 assert.deepEqual(service.conversation(id).completed,[0]);
 const restored=createAgentGuideService(snapshots,ai,{storage});
 assert.equal(restored.conversation(id).position,1);assert(restored.conversation(id).explanations[0]);
 const local=sanitizeDeepWorkspace({mode:'deep',activeId:id,records:{[id]:restored.conversation(id)}});
 assert(local.records[id].explanations[0],'Generated text must survive local offline sanitization');
 assert.equal(local.records[id].completed[0],0);
 const device={deepReviews:{[JSON.stringify(['repo','snapshot-1'])]:{...local,records:{[id]:{...local.records[id],position:0}}}}};
 const ui=createDeepReviewUI({getState:()=>({snapshot:{repoId:'repo',snapshotId:'snapshot-1',files:[{...files[0],source}]},online:false,aiEnabled:false,demo:false}),getData:()=>device,save:()=>{},render:()=>{},apiFetch:()=>{throw Error('Offline reading must not call the laptop');},jump:()=>{}});
 assert.match(ui.html().replace(/<[^>]*>/g,''),/These lines define the values used by this file/);
 service.close();restored.close();
}
const slow=createAgentGuideService(snapshots,{generate(_prompt,{signal}){return new Promise(resolve=>{signal.addEventListener('abort',()=>resolve({status:499,body:{error:'Stopped.'}}));});}});
const slowId='deep-cancellation-001';slow.startDeep({requestId:slowId,snapshotId:'snapshot-1'});
slow.deepSection({requestId:'deep-cancel-request-001',conversationId:slowId,index:0});
await Promise.resolve();slow.runs.cancel('deep-cancel-request-001');
assert.equal((await slow.runs.wait('deep-cancel-request-001')).status,'cancelled');
assert.equal(Object.keys(slow.conversation(slowId).explanations).length,0);
slow.close();
console.log('Deep review passed: contiguous coverage, notices, citations, lazy Codex and Claude generation, and saved progress.');
