import assert from 'node:assert/strict';
import { createGuideRuns } from '../guide-runs.mjs';
const registry = createGuideRuns();
const id = 'stable-request-0001', input = { snapshotId: 'snapshot-a', conversationId: 'main', question: 'Explain' };
let executions = 0, finish, callbacks;
const execute = async (_, options) => { executions++; callbacks = options; options.onDelta('First'); return new Promise(resolve => { finish = resolve; }); };
assert.equal(registry.start(id, input, execute).status, 'running');
await Promise.resolve();
assert.equal(registry.start(id, input, execute).text, 'First');
assert.equal(executions, 1);
assert.throws(() => registry.start(id, { ...input, snapshotId: 'snapshot-b' }, execute), error => error.status === 409);
assert.throws(() => registry.start('stable-request-0002', input, execute), error => error.status === 429);
const updates = []; const disconnect = registry.subscribe(id, value => updates.push(value));
disconnect(); callbacks.onDelta(' after disconnect');
assert.equal(callbacks.signal.aborted, false);
const reconnected = []; registry.subscribe(id, value => reconnected.push(value));
assert.equal(reconnected[0].text, 'First after disconnect');
const revision = reconnected[0].revision;
assert.equal(registry.get(id, revision), null);
callbacks.onActivity({ tool: 'review_read', path: 'caller.js' });
assert.equal(registry.get(id).activity.path, 'caller.js');
callbacks.onProgress({phase:'overviews',completed:1,total:3,fileOverviews:{'a.js':'Ready'},overviewStatus:{'a.js':'ready'}});
assert.equal(registry.get(id).progress.fileOverviews['a.js'],'Ready');
finish({ text: 'Final' });
assert.equal((await registry.wait(id)).status, 'completed');
assert.equal(registry.start(id, input, execute).status, 'completed'); assert.equal(executions, 1);
const cancelId = 'stable-request-0003';
registry.start(cancelId, input, async (_, { signal }) => new Promise((resolve, reject) => { signal.addEventListener('abort', () => reject(new Error('cancelled'))); }));
await Promise.resolve(); registry.cancel(cancelId);
assert.equal((await registry.wait(cancelId)).status, 'cancelled');
const bounded = createGuideRuns({ maxRuns: 1, maxReplyBytes: 10 });
bounded.start(id, input, async (_, { onDelta }) => { onDelta('12345678901'); });
assert.equal((await bounded.wait(id)).status, 'failed');
bounded.start(cancelId, input, async () => 'ok'); await bounded.wait(cancelId);
assert.throws(() => bounded.get(id), error => error.status === 404);
assert.throws(() => registry.start('../escape', input, execute), error => error.status === 400);
const immediate = createGuideRuns(); let started = false;
immediate.start(id, input, async () => { started = true; }); immediate.close();
assert.equal((await immediate.wait(id)).status, 'cancelled'); assert.equal(started, false);
assert.throws(() => createGuideRuns({ maxRuns: 0 }), /positive integers/);
const lanes = createGuideRuns(); let release;
const hold = new Promise(resolve => { release = resolve; });
lanes.start('prefetch-lane-run-01', { snapshotId: 's', conversationId: 'c' }, () => hold, { lane: 'prefetch' });
assert.equal(lanes.start('main-lane-run-00001', { snapshotId: 's', conversationId: 'c' }, async () => 'ok').status, 'running', 'A background prefetch must not block a question.');
assert.throws(() => lanes.start('prefetch-lane-run-02', { snapshotId: 's', conversationId: 'c' }, async () => 'ok', { lane: 'prefetch' }), error => error.status === 429);
release(); await lanes.wait('prefetch-lane-run-01');
console.log('Guide runs passed: idempotent requests, reconnect without restart, explicit cancellation, snapshot binding, bounded replies, eviction and prefetch lanes.');
