import { escapeHtml as esc } from './render.js';
import { randomId } from './platform.js';
import { errorMessage } from './transport.js';

const validId = id => typeof id === 'string' && /^[a-zA-Z0-9_-]{16,80}$/.test(id);
const keyFor = snapshot => JSON.stringify([snapshot.repoId, snapshot.snapshotId]);
export function sanitizeDeepWorkspace(value) {
  const records = {};
  for (const record of Object.values(value?.records || {}).slice(0,128)) {
    if (!validId(record?.id) || typeof record.snapshotId !== 'string' || !Array.isArray(record.sections)) continue;
    const sections = record.sections.filter(s=>s&&typeof s.path==='string'&&typeof s.fileId==='string'&&['code','summary'].includes(s.kind)).map((s,i)=>({id:String(i),path:s.path.slice(0,4096),fileId:s.fileId,kind:s.kind,side:'new',startLine:s.kind==='code'&&Number.isSafeInteger(s.startLine)?s.startLine:null,endLine:s.kind==='code'&&Number.isSafeInteger(s.endLine)?s.endLine:null,summary:typeof s.summary==='string'?s.summary.slice(0,1000):null}));
    if (!sections.length) continue;
    const explanations = {};
    for (const [index,item] of Object.entries(record.explanations||{})) {
      if (!/^\d+$/.test(index) || Number(index)>=sections.length || !item || !Array.isArray(item.explanations)) continue;
      explanations[index]={explanations:item.explanations.slice(0,12).filter(e=>e&&Number.isSafeInteger(e.startLine)&&Number.isSafeInteger(e.endLine)&&typeof e.text==='string').map(e=>({startLine:e.startLine,endLine:e.endLine,text:e.text.slice(0,1400)})),pointers:(Array.isArray(item.pointers)?item.pointers:[]).slice(0,4).filter(p=>p&&typeof p.text==='string'&&p.citation&&typeof p.citation.path==='string').map(p=>({text:p.text.slice(0,500),citation:{path:p.citation.path,fileId:p.citation.fileId||null,side:p.citation.side,startLine:p.citation.startLine,endLine:p.citation.endLine}})),narration:typeof item.narration==='string'?item.narration.slice(0,15000):''};
    }
    records[record.id]={id:record.id,mode:'deep',snapshotId:record.snapshotId,title:'Deep file review',sections,position:Number.isSafeInteger(record.position)?Math.max(0,Math.min(sections.length-1,record.position)):0,completed:(Array.isArray(record.completed)?record.completed:[]).filter(n=>Number.isSafeInteger(n)&&n>=0&&n<sections.length),explanations,runId:validId(record.runId)?record.runId:null,scroll:Number.isFinite(record.scroll)&&record.scroll>=0?record.scroll:0};
  }
  const pending=value?.pending;
  return {mode:value?.mode==='deep'?'deep':'overview',activeId:validId(value?.activeId)?value.activeId:'',records,pending:pending&&validId(pending.requestId)&&validId(pending.recordId)&&Number.isSafeInteger(pending.index)?{requestId:pending.requestId,recordId:pending.recordId,index:pending.index,prefetch:Boolean(pending.prefetch),acknowledged:Boolean(pending.acknowledged)}:null};
}

export function createDeepReviewUI({getState,getData,save,render,apiFetch,showSection}) {
  let error='',polling=false,retryTimer,prefetchTimer,audio=null,audioUrl=null,audioIndex=-1,audioLoading=false,audioReady=false,audioGeneration=0,focusedSection='';
  const workspace=()=>{const s=getState();if(!s.snapshot)return null;getData().deepReviews||={};return getData().deepReviews[keyFor(s.snapshot)]||={mode:'overview',activeId:'',records:{},pending:null};};
  const current=()=>{const w=workspace();return w?.records[w.activeId];};
  const enabled=()=>getState().online&&getState().aiEnabled&&!getState().demo;
  async function request(path,input) {
    const response=await apiFetch(`/api/guide/deep/${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});
    const body=await response.json();if(!response.ok){const failure=new Error(errorMessage(body));failure.status=response.status;throw failure;}return body;
  }
  function stopAudio(){audioGeneration++;audio?.pause();if(audioUrl)URL.revokeObjectURL(audioUrl);audio=null;audioUrl=null;audioIndex=-1;audioLoading=false;audioReady=false;}
  function focusCurrent(force=false,reveal=force){const record=current(),position=record?.position,section=record?.sections[position];if(!section)return;const key=`${record.id}:${position}`;if(!force&&focusedSection===key)return;focusedSection=key;queueMicrotask(()=>{if(current()?.id===record.id&&current()?.position===position)showSection(section,{reveal});});}
  function html() {
    const record=current(),w=workspace();if(!record)return '<p class="guide-intro">Choose Deep file review to start.</p>';
    const section=record.sections[record.position],explanation=record.explanations[record.position];
    const captured=getState().snapshot?.files.find(file=>file.id===section.fileId),sourceReady=typeof captured?.source==='string';
    const fileSections=record.sections.filter(s=>s.fileId===section.fileId),fileIndex=fileSections.findIndex(s=>s.id===section.id)+1;
    const files=[...new Set(record.sections.map(s=>s.fileId))],fileNumber=files.indexOf(section.fileId)+1;
    const complete=record.completed.length;
    return `<section class="walkthrough deep-review"><p class="eyebrow">DEEP FILE REVIEW · FILE ${fileNumber} OF ${files.length} · SECTION ${fileIndex} OF ${fileSections.length}</p><h3>${esc(section.path)}</h3><p>${complete} of ${record.sections.length} sections visited. This progress does not mark any file reviewed or approved.</p>
      <label class="deep-file-picker">Changed file <select id="deep-file">${files.map(id=>{const first=record.sections.findIndex(s=>s.fileId===id),item=record.sections[first];return `<option value="${first}" ${id===section.fileId?'selected':''}>${esc(item.path)}</option>`;}).join('')}</select></label>
      ${section.kind==='summary'?`<div class="deep-notice"><strong>Coverage notice</strong><p>${esc(section.summary)}</p></div>`:`<div class="deep-location"><p>${sourceReady?`Lines ${section.startLine}–${section.endLine} are highlighted in the main reader, including unchanged lines.`:`Lines ${section.startLine}–${section.endLine} will appear in the main reader when captured source is available on this device.`}</p><button class="secondary-button" data-deep="show-code">${sourceReady?'View highlighted code':'View file'}</button></div>
      ${explanation?`<div class="deep-explanation">${explanation.explanations.map((item,index)=>`<div class="deep-explanation-item"><button class="agent-step-link" data-deep-range="${index}">Lines ${item.startLine}–${item.endLine}</button><p>${esc(item.text)}</p></div>`).join('')}</div><div class="deep-pointers"><strong>Things to double-check</strong>${explanation.pointers.length?`<ul>${explanation.pointers.map((pointer,index)=>`<li>${esc(pointer.text)} <button class="agent-step-link" data-deep-pointer="${index}">${esc(pointer.citation.path)} · ${pointer.citation.startLine}–${pointer.citation.endLine}</button></li>`).join('')}</ul>`:'<p>No specific concern identified from captured context. This does not verify the change.</p>'}</div><button class="secondary-button" data-deep="play" ${audioLoading?'disabled':''}>${audioLoading?'Preparing audio…':audio&&audioIndex===record.position&&!audio.paused?'Pause':audioReady?'Play ready audio':'Play section'}</button>${audioReady?'<p role="status">Audio is ready. Tap Play ready audio to start it in this browser.</p>':''}`:`<p role="status">${w.pending?.index===record.position?'Explaining this section…':enabled()?'Explanation ready to request.':getState().online?'Connect Codex or Claude Code on the laptop to generate this section.':'Previously generated sections remain available offline.'}</p>${enabled()&&!w.pending?'<button class="secondary-button" data-deep="explain">Explain this section</button>':''}`}`}
      ${error?`<p class="guide-error" role="alert">${esc(error)}</p>`:''}${w.pending?'<button class="secondary-button" data-deep="stop">Stop explanation</button>':''}
      <div class="walk-controls"><button class="secondary-button" data-deep="previous" ${record.position===0?'disabled':''}>Back</button><button class="primary-button" data-deep="next" ${record.position===record.sections.length-1?'disabled':''}>Next section</button></div><button class="secondary-button" data-deep="new">New review</button></section>`;
  }
  async function start(){if(!getState().online)return;const id=randomId(),snapshotId=getState().snapshot.snapshotId;error='';try{const {conversation}=await request('start',{requestId:id,snapshotId});const w=workspace();w.records[id]=conversation;w.activeId=id;w.mode='deep';await save();render(false);queueMicrotask(()=>ensureSection(0));}catch(e){error=errorMessage(e.message);render();}}
  async function poll(){const w=workspace(),pending=w?.pending;if(!pending||polling||!getState().online)return;polling=true;clearTimeout(retryTimer);try{
    if(!pending.acknowledged){const model=getState().aiProvider==='codex'?getData().preferences.model||undefined:undefined,effort=getState().aiProvider==='codex'?getData().preferences.effort||undefined:undefined;const result=await request('section',{requestId:pending.requestId,conversationId:pending.recordId,index:pending.index,prefetch:pending.prefetch,model,effort});pending.acknowledged=true;if(result.cached){w.records[pending.recordId]=result.conversation;w.pending=null;await save();render();return;}await save();}
    const response=await apiFetch(`/api/guide/run?id=${encodeURIComponent(pending.requestId)}`);const {run}=await response.json();if(!response.ok||!run)throw new Error('The section run is unavailable.');
    if(!['running','stopping'].includes(run.status)){const response=await apiFetch(`/api/guide/conversation?id=${encodeURIComponent(pending.recordId)}`);const {conversation}=await response.json();if(response.ok&&conversation?.mode==='deep'){const local=w.records[pending.recordId];w.records[pending.recordId]={...conversation,position:local.position,completed:local.completed,scroll:local.scroll};}w.pending=null;error=run.status==='completed'?'':run.error||'Section explanation stopped.';await save();render();if(run.status==='completed')schedulePrefetch();}
    else render();
  }catch(e){if(e.status>=400&&e.status<500&&e.status!==429){w.pending=null;error=errorMessage(e.message);}else error=`${errorMessage(e.message)} Reconnecting will resume this section.`;render();}finally{polling=false;if(w.pending)retryTimer=setTimeout(poll,error?5000:1000);}}
  function ensureSection(index,prefetch=false){const w=workspace(),record=current();if(!record||!enabled()||w.pending||record.explanations[index]||record.sections[index]?.kind!=='code')return;w.pending={requestId:randomId(),recordId:record.id,index,prefetch,acknowledged:false};error='';save();render();poll();}
  function schedulePrefetch(){clearTimeout(prefetchTimer);const r=current();if(!r)return;const next=r.position+1;if(!r.sections[next]||r.explanations[next]||r.sections[next].kind!=='code')return;prefetchTimer=setTimeout(()=>{if(getState().guideMode==='walkthrough'&&enabled()&&!workspace().pending&&current()===r)ensureSection(next,true);},2000);}
  async function cancelPrefetch(){clearTimeout(prefetchTimer);const w=workspace();if(!w?.pending?.prefetch)return;for(let attempt=0;polling&&attempt<30;attempt++)await new Promise(resolve=>setTimeout(resolve,100));const pending=w.pending;if(!pending?.prefetch)return;
    if(pending.acknowledged&&getState().online){await apiFetch('/api/guide/stop',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:pending.requestId})}).catch(()=>{});for(let attempt=0;attempt<30;attempt++){const response=await apiFetch(`/api/guide/run?id=${encodeURIComponent(pending.requestId)}`).catch(()=>null);const run=response?.ok?(await response.json()).run:null;if(!run||!['running','stopping'].includes(run.status))break;await new Promise(resolve=>setTimeout(resolve,100));}}
    if(w.pending===pending){w.pending=null;clearTimeout(retryTimer);retryTimer=null;await save();render();}
  }
  async function move(index){clearTimeout(prefetchTimer);const r=current();if(!r||index<0||index>=r.sections.length)return;if(workspace().pending?.prefetch&&workspace().pending.index!==index)await cancelPrefetch();stopAudio();if(index>r.position&&!r.completed.includes(r.position))r.completed.push(r.position);r.position=index;r.scroll=0;error='';await save();render(false);if(getState().online)request('advance',{conversationId:r.id,position:index,completed:r.completed}).catch(()=>{});ensureSection(index);}
  async function playChunk(r,index,chunk){stopAudio();const generation=audioGeneration;audioLoading=true;error='';render();try{const response=await apiFetch('/api/guide/deep/speech',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId:r.id,index,chunk,voice:'af_heart'}),signal:AbortSignal.timeout(660000)});if(!response.ok){const body=await response.json();throw new Error(errorMessage(body));}const blob=await response.blob();if(generation!==audioGeneration||current()?.id!==r.id||current()?.position!==index)return;const total=Math.max(1,Number(response.headers.get('x-patchwork-audio-chunks'))||1);audioUrl=URL.createObjectURL(blob);audio=new Audio(audioUrl);audioIndex=index;audio.onended=()=>{if(generation!==audioGeneration)return;if(chunk+1<total)playChunk(r,index,chunk+1);else{stopAudio();render();}};audio.onerror=()=>{if(generation!==audioGeneration)return;stopAudio();error='Audio could not play on this device. Try Play again.';render();};try{await audio.play();}catch(playbackError){if(playbackError?.name!=='NotAllowedError')throw playbackError;audioReady=true;}}catch(e){if(generation===audioGeneration)error=e?.name==='NotSupportedError'?'Audio could not play on this device.':errorMessage(e.message);}finally{if(generation===audioGeneration){audioLoading=false;render();}}}
  async function play(){const r=current(),index=r?.position;if(!r?.explanations[index])return;if(audio&&audioIndex===index){if(audio.paused){try{await audio.play();audioReady=false;error='';}catch(e){if(e?.name==='NotAllowedError'){audioReady=true;error='Browser playback is still blocked. Tap Play again after allowing audio for this page.';}else error='Audio could not play on this device. Try Play again.';}}else audio.pause();render();return;}await playChunk(r,index,0);}
  function bind(root){const w=workspace(),r=current();root.querySelector('#deep-file')?.addEventListener('change',e=>move(Number(e.target.value)));root.querySelectorAll('[data-deep-range]').forEach(el=>el.addEventListener('click',()=>{const item=current().explanations[current().position].explanations[Number(el.dataset.deepRange)],section=current().sections[current().position];showSection({...section,startLine:item.startLine,endLine:item.endLine},{reveal:true});}));root.querySelectorAll('[data-deep-pointer]').forEach(el=>el.addEventListener('click',()=>showSection({kind:'code',...current().explanations[current().position].pointers[Number(el.dataset.deepPointer)].citation},{reveal:true})));
    root.querySelectorAll('[data-deep]').forEach(el=>el.addEventListener('click',async()=>{switch(el.dataset.deep){case 'previous':await move(current().position-1);break;case 'next':await move(current().position+1);break;case 'show-code':focusCurrent(true);break;case 'explain':ensureSection(current().position);break;case 'play':await play();break;case 'stop':if(workspace().pending){await apiFetch('/api/guide/stop',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:workspace().pending.requestId})}).catch(()=>{});poll();}break;case 'new':await cancelPrefetch();stopAudio();focusedSection='';workspace().mode='overview';await save();render();break;}}));
    if(w?.pending&&!polling&&!retryTimer)queueMicrotask(poll);if(r&&!r.explanations[r.position]&&enabled()&&!w.pending)queueMicrotask(()=>ensureSection(r.position));focusCurrent();}
  return {html,bind,start,current,workspace,stopAudio,cancelPrefetch,focusCurrent};
}
